[package]
name = "mojo"
version = "0.1.0"
edition = "2021"
authors = ["nijaru"]
publish = false
description = "Modern Mojo language support for Zed"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.2.0"